title: Edusemi-Plus
description: 半導体産業と社会・AIをつなぐ応用教材
lang: ja

# リポジトリ Pages 用（/ユーザー/リポジトリ）公開
url: "https://samizo-aitl.github.io"
baseurl: "/Edusemi-Plus"      # ルート公開なら "" に

# テーマ
theme: minima

# Markdown エンジン：kramdown + GFM
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Sass（minima + 自前SCSSのビルド最適化）
sass:
  style: compressed

# タイムゾーン / きれいなURL
timezone: Asia/Tokyo
permalink: pretty

# 既定レイアウト（書き忘れ防止）
defaults:
  - scope:
      path: ""
    values:
      layout: default

# GitHub Pages で不要なものは除外
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
