title: Edusemi-Plus
description: 半導体産業と社会・AIをつなぐ応用教材
lang: ja

# リポジトリ Pages 用（末尾スラなし / リポ名は大文字小文字まで一致）
url: "https://samizo-aitl.github.io"
baseurl: "/Edusemi-Plus"

# テーマ
theme: minima

# Markdown エンジン：kramdown + GFM
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
  hard_wrap: false

# ビルド安定化
timezone: Asia/Tokyo
permalink: pretty

# GitHub Pages で不要なものは除外
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
